import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Downloads the generated website as a ZIP file
 * with index.html, styles.css, and script.js
 */
export async function downloadZip(html: string, css: string, js: string, siteName: string = 'falcon-site') {
  const zip = new JSZip();

  // Ensure HTML references the external CSS and JS files
  const fullHtml = html.includes('styles.css')
    ? html
    : html.replace('</head>', '  <link rel="stylesheet" href="styles.css">\n</head>')
        .replace('</body>', '  <script src="script.js"></script>\n</body>');

  zip.file('index.html', fullHtml);
  zip.file('styles.css', css);
  zip.file('script.js', js);

  // Add a simple README
  zip.file('README.md', `# ${siteName}\n\nGenerated by Falcon Web-Builder 🦅\n\nOpen \`index.html\` in your browser to view the site.\n`);

  const blob = await zip.generateAsync({ type: 'blob' });
  const filename = `${siteName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.zip`;
  saveAs(blob, filename);
}
